### numpy array and basics


In [3]:
import numpy as np 


### creatiing array from list

In [6]:
arr_1d = np.array([3,5,6,4,8,6])
print(arr_1d)
arr_2d = np.array([[2,3],[4,5]])
print(arr_2d)

[3 5 6 4 8 6]
[[2 3]
 [4 5]]


### list vs numpy array

In [7]:
import time as t
print(t.time())

1780058665.026064


In [9]:
full = np.full((3,3), 7)
print(full)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [12]:
sec = np.random.random((2,3))
print("random array : \n", sec)
series = np.arange(0, 11, 2)
print(series)

random array : 
 [[0.45858296 0.47849551 0.71993736]
 [0.72126882 0.39709069 0.10706872]]
[ 0  2  4  6  8 10]


### vector matrix, tensor