this is phase 3.

In [24]:
import numpy as np

marks = np.array([
    [85, 90, 78],
    [72, 88, 91],
    [95, 89, 93],
    [60, 75, 70],
    [88, 92, 85]
])

Rows = Students
Columns = Math, Physics, Chemistry

In [25]:
print("shape of the data ", np.shape(marks))

#marks of third student.

print("Marks of third student:", marks[2])

shape of the data  (5, 3)
Marks of third student: [95 89 93]


In [26]:
print("marks of physics : ", marks[:, 1])

marks of physics :  [90 88 89 75 92]


In [27]:
# total marks of each student
print("total  marks of all student",  np.sum(marks[:, :]))

print("Total marks of each student:", np.sum(marks, axis=1)) # axis=0 → operate down columns  axis=1 → operate across rows
total_marks_subjetwise = np.sum(marks, axis=0)
print(total_marks_subjetwise)

total  marks of all student 1251
Total marks of each student: [253 251 277 205 265]
[400 434 417]


In [28]:
#Find the average marks of each student.
print("average marks of the students", np.average(marks,axis=1))

average marks of the students [84.33333333 83.66666667 92.33333333 68.33333333 88.33333333]


In [29]:
#Find the highest mark in the entire dataset.

print("heighest marks in db", np.max(marks))

print("Highest mark in each subject: ", np.max(marks, axis=0))

print("lowest mark in the entire dataset: ", np.min(marks))

heighest marks in db 95
Highest mark in each subject:  [95 92 93]
lowest mark in the entire dataset:  60


In [30]:
#Find the average marks subject-wise.
print("the average marks subject-wise: ", np.mean(marks, axis=0))

# Find students whose Math marks are greater than 80.#
print(marks[marks[:, 0] > 80])

the average marks subject-wise:  [80.  86.8 83.4]
[[85 90 78]
 [95 89 93]
 [88 92 85]]


In [31]:
#Add 5 grace marks to every Chemistry score.
print(marks)
marks[:, 2] += 5
print("added grace marks  to chemistry: ",marks)

[[85 90 78]
 [72 88 91]
 [95 89 93]
 [60 75 70]
 [88 92 85]]
added grace marks  to chemistry:  [[85 90 83]
 [72 88 96]
 [95 89 98]
 [60 75 75]
 [88 92 90]]


# Dataset

In [32]:
import numpy as np

data = np.array([
    [85, 90, 78],
    [72, 88, 91],
    [95, 89, 93],
    [60, 75, 70],
    [88, 92, 85]
])

In [34]:
print("maths marks graeter than 80", marks[marks[:,0]>80])

#Sort all values in the dataset from smallest to largest.

sorted_data = np.sort(data.flatten())
print("sorted data : ", sorted_data)

maths marks graeter than 80 [[85 90 83]
 [95 89 98]
 [88 92 90]]
sorted data :  [60 70 72 75 78 85 85 88 88 89 90 91 92 93 95]


In [43]:
print("median of data : ", np.median(marks))

reshaped_data = data.flatten().reshape(3,5)
print(reshaped_data)

flat = data.flatten()
count = flat[flat>85]
print(count.size)

print(np.sum(flat > 85))

median of data :  88.0
[[85 90 78 72 88]
 [91 95 89 93 60]
 [75 70 88 92 85]]
8
8
